### ISSUE TITLE
Authservice erkennt eingeloggten nutzer nicht

### ISSUE THREAD

**Issue by StephanUnfried** [REMEXLabs/OpenAPE#124]
@Lukas84 Ich habe meinen Branch für den geänderten Resourcenfolder und gefixte Resource Description verwaltung jetzt getestet und gemerget.
@jaufmann Allerdings habe ich dazu temporär den Auth service im Code deaktiviert, da er mich immer geblockt hat, obwohl ich mich auf der Seite angemeldet hatte. Kann leider nicht sagen warum. Error war 401: Unauthorized.

**Comment by StephanUnfried** [comment]
@jaufmann never mind, hab mein altes test interface benutzt, das sendet natürlich keinen token. wie genau funktioniert der eigentlich gehört der in den Header?

**Comment by Lukas84** [comment]
Der Token gehört in das „Authorisation“ Feld im Header

 

Von: StephanUnfried [mailto:notifications@github.com] 
Gesendet: Montag, 7. August 2017 10:30
An: REMEXLabs/OpenAPE <OpenAPE@noreply.github.com>
Cc: Lukas84 <smirek@hdm-stuttgart.de>; Mention <mention@noreply.github.com>
Betreff: Re: [REMEXLabs/OpenAPE] Authservice erkennt eingeloggten nutzer nicht (#124)

 

@jaufmann <https://github.com/jaufmann>  never mind, hab mein altes test interface benutzt, das sendet natürlich keinen token. wie genau funktioniert der eigentlich gehört der in den Header?
