### ISSUE TITLE
Resource Rest Header mit Group Acces Rights

### ISSUE THREAD

**Issue by StephanUnfried** [REMEXLabs/OpenAPE#125]
Branch https://github.com/REMEXLabs/OpenAPE/tree/ResourceAuthViaHeader

**Comment by StephanUnfried** [comment]
needs tests

**Comment by StephanUnfried** [comment]
@abltb bekommt eine Resource ein GroupAccessRight object oder eine Liste davon?

**Comment by abltb** [comment]
Eine Liste.

Mit freundlichen Grüßen

Tobias Ableitner

Am 07.08.2017 um 10:34 schrieb StephanUnfried:

**Comment by StephanUnfried** [comment]
done
