### ISSUE TITLE
getResource is returning a jbos object

### ISSUE THREAD

**Issue by jaufmann** [REMEXLabs/OpenAPE#146]
see http://imgur.com/a/FsAh3

**Comment by StephanUnfried** [comment]
WTF

**Comment by StephanUnfried** [comment]
Ich verstehs nicht, ich hab grad nochmal den code durchgeschaut und das passt eigentlich alles. Und die Response kann auch nur vom typ File sein.

@jaufmann auf welchem Branch und welchem Commit arbeitest denn du?

**Comment by jaufmann** [comment]
auf VelocityMyResources https://github.com/REMEXLabs/OpenAPE/tree/velocityMyResources

**Comment by StephanUnfried** [comment]
Das ist extem seltsam, get auf /api/resources/:resource-id ist nicht in der lade etwas zurück zu geben was nicht vom typ file ist.
Merge mal bitte den newMaster, falls es dann noch besteht schau ichs mir genauer an.
Wie dringend ist das?

**Comment by jaufmann** [comment]
Nein, ich kann soweit serverseitig mir alle elemente generieren. Aber ist mir eben beim testen aufgefallen, dass beim konsumieren der GET-Schnittstelle nur ein jbos-Object und kein JSON bzw. XML Response zurückkommt. Hat aber momentan keine hohe Dringlichkeit.
