### ISSUE TITLE
Create REST endpoints for context services

### ISSUE THREAD

**Issue by Lukas84** [REMEXLabs/OpenAPE#19]
setup an SPARK Server and make Endpoints from ISO 24752-8 Sections 7.2 till 7.5 available.

**Comment by StephanUnfried** [comment]
Ich hab mal etwas basiscode eingefügt und dafür gesorgt, dass Lambdaausdrücke funktionieren. (Maven arbeitet standardmäßig mit Java 1.5 -.-)
Aktuell sitze ich an dem Problem, dass maven die Klassen aus den anderen Modulen nicht finded. Problem detailiert: Ich versuche von UserContextRESTInterface im api modul auf UserContextRequestHandler im server modul zuzugreifen, weil das interface die restanfrage entgegen nimmt und der handler sie verarbeiten soll. mvn install oder mvn package gibt nun zurück, dass aber nicht gefunden wird. Hab schon ein bisschen nach Lösungen gesucht, mach jetzt aber erstmal schluss.

**Comment by Lukas84** [comment]
Hi,

auf die schnelle: wenn ihr ein Modul in einem anderen verwenden wollt, dann müsst ihr es auch als dependency in der pom Datei angeben.

 

Ich konnte jetzt in euren Code noch nicht reinschauen, mir scheint es im Moment aber etwas ungewöhnlich, dass die API auf den Handler zugreift. Normalerweise versucht man die API immer nur in anderen Paketen zu verwenden.

Vielleicht habe ich da aber auch was falsch vrstanden oder muss mir euren Code mal anschauen.Denkt nochmal drüber nach und dann lasst uns nochmals drüber reden. Ihr habt das ja auch nicht ohne Grund so gemacht. 

 

Ihr müsst allerdings aufpassen, dass zwischen den Modulen keine Zirkelbezüge bezüglich der aabhängigkeiten auftreten, sonst streikt Maven nämlich.

 

Gut, dass ihr das Hauptproject schon von jar auf pom umgestellt habt.

 

Viele Grüße

Lukas

Von: StephanUnfried [mailto:notifications@github.com] 
Gesendet: Mittwoch, 26. Oktober 2016 18:29
An: REMEXLabs/OpenAPE <OpenAPE@noreply.github.com>
Cc: Lukas84 <smirek@hdm-stuttgart.de>; Author <author@noreply.github.com>
Betreff: Re: [REMEXLabs/OpenAPE] Create REST endpoints for context services (#19)

 

Ich hab mal etwas basiscode eingefügt und dafür gesorgt, dass Lambdaausdrücke funktionieren. (Maven arbeitet standardmäßig mit Java 1.5 -.-)
Aktuell sitze ich an dem Problem, dass maven die Klassen aus den anderen Modulen nicht finded. Problem detailiert: Ich versuche von UserContextRESTInterface im api modul auf UserContextRequestHandler im server modul zuzugreifen, weil das interface die restanfrage entgegen nimmt und der handler sie verarbeiten soll. mvn install oder mvn package gibt nun zurück, dass aber nicht gefunden wird. Hab schon ein bisschen nach Lösungen gesucht, mach jetzt aber erstmal schluss.

**Comment by StephanUnfried** [comment]
Hi,


Zu der Struktur, wie ich sie mir überlegt habe:

Ich dachte zuerst alles, was zum server gehört, inklusive der REST Schnittstellen, kommt in das server Modul und das HTML Interface kommt in das API Modul.

Aber es gab ja ein Issue, das gesagt hat, dass gesagt hat, dass die Klassen UserContext, Preference und Context ins API Modul verschoben werden sollen. Daraus habe ich geschlossen, dass dort die REST Schnittstelle hin soll und habe sie angefangen dort zu implementieren. Da die Anfragenverarbeiteung für mich aber nicht zur API sondern zum server gehören habe ich dort dann den Trennstrich gezogen und hätte die Anfragenhändler, in denen die Methoden stehen, die vom Restinterface aufgerufen werden, sowie den Datenbankanschluss im server modul erstellt.

Das heißt Im Restinterface binde ich aktuell die Handler ein um auf die Methoden zugreifen zu können.


Generell würde ich das ganze aber gerne so sortieren, wie ich mir das ursprünglich gedacht habe.

Nebenbei: So wie es gerade ist müsste man UserContext ins Hauptptoprojekt ziehen, da sowohl api als auch servermodul mit Instanzen davon umgehen können müssen.


Danke für den Lösungsansatz ich danke das sollte das Problem lösen,

viele Grüße,

Stephan

**Comment by Lukas84** [comment]
Hi,

deine ursprüngliche Idee ist glaube ich ziemlich richtig.

 

Ich wollte in die API eigentlich nur die Context Klassen auslagern, damit diese z.B. auch von einem Java Client genutzt werden können.

 

In eurem Teil kann es gut sein, dass es überhaupt kein HTML Interface geben wird das direkt vom Server angeboten wird, höchstens eine Java Library.

 

Falls es zu verwirrend wird meldet euch nochmal, ansonsten vertraut auf eur Bauchgefühl bis Mittwoch. Ein paar Klassen hin und herzuschieben ist ja mit refactoring kein Problem.

 

Viele Grüße

Lukas 

 

Von: StephanUnfried [mailto:notifications@github.com] 
Gesendet: Donnerstag, 27. Oktober 2016 17:39
An: REMEXLabs/OpenAPE <OpenAPE@noreply.github.com>
Cc: Lukas84 <smirek@hdm-stuttgart.de>; Author <author@noreply.github.com>
Betreff: Re: [REMEXLabs/OpenAPE] Create REST endpoints for context services (#19)

 

Hi,


Zu der Struktur, wie ich sie mir überlegt habe:

Ich dachte zuerst alles, was zum server gehört, inklusive der REST Schnittstellen, kommt in das server Modul und das HTML Interface kommt in das API Modul.

Aber es gab ja ein Issue, das gesagt hat, dass gesagt hat, dass die Klassen UserContext, Preference und Context ins API Modul verschoben werden sollen. Daraus habe ich geschlossen, dass dort die REST Schnittstelle hin soll und habe sie angefangen dort zu implementieren. Da die Anfragenverarbeiteung für mich aber nicht zur API sondern zum server gehören habe ich dort dann den Trennstrich gezogen und hätte die Anfragenhändler, in denen die Methoden stehen, die vom Restinterface aufgerufen werden, sowie den Datenbankanschluss im server modul erstellt.

Das heißt Im Restinterface binde ich aktuell die Handler ein um auf die Methoden zugreifen zu können.


Generell würde ich das ganze aber gerne so sortieren, wie ich mir das ursprünglich gedacht habe.

Nebenbei: So wie es gerade ist müsste man UserContext ins Hauptptoprojekt ziehen, da sowohl api als auch servermodul mit Instanzen davon umgehen können müssen.


Danke für den Lösungsansatz ich danke das sollte das Problem lösen,

viele Grüße,

Stephan

**Comment by StephanUnfried** [comment]
Hi,

Alles Klar, ich be ich habe verstanden wie es aussehen soll. Datenklassen, von denen die Objekte abgeleitet werden, mit denen wir tatsählich hantieren wollen in die API, Serverfunktionalität in den Server. Das macht Sinn.

Gerade bin ich leider anderweitig eingebunden, ich hoffe ich komme bis mittwoch dazu die Struktur zu berichtigen und das Rest Interface grundlegend einzurichten. Wahrscheinlich komm ich Sonntag oder Dienstag dazu,


Vielen Dank für die Info, viele grüße, bis Mittwoch,

Stephan

**Comment by StephanUnfried** [comment]
Die User context rest api ist soweit fertig, auch wenn ich sie gerne noch testen würde.
