### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nok** [REMEXLabs/OpenAPE#25]
Where is the license file? 🌵

**Comment by cstrobbe** [comment]
I like the cactus!

**Comment by StephanUnfried** [comment]
Sie ist da :)

**Comment by nok** [comment]
It's almost done. I would either replace the license file to the [root directory](https://github.com/REMEXLabs/OpenAPE), or add a linked hint about the chosen license to the [readme](https://github.com/REMEXLabs/OpenAPE/blob/master/README.md) file. Then it should be clear. 👍 

> Most people place their license text in a file named LICENSE.txt (or LICENSE.md) in the root of the repository; here's an example from Hubot.

> As long as your intention is clear, you can place your license information wherever you like. Some projects only include a descriptive line in the project's README (e.g., "This project is licensed under the terms of the MIT license."). However, to avoid any potential ambiguity, it's best to include the license file with your project as well.

https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository
