### ISSUE TITLE
Eclipse und Maven einrichten

### ISSUE THREAD

**Issue by StephanUnfried** [REMEXLabs/OpenAPE#3]
Eclipse und Maven installieren und das Projekt dort einrichten. Bezwihungsweise die IDE der Wahl. Das Issue wird geschlossen, wenns bei allen funktioniert

**Comment by Lukas84** [comment]
Maven könnt ihr hier runterladen:
[http://maven.apache.org/download.cgi](http://maven.apache.org/download.cgi)

Hier gibt es [Maven in five minutes](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html)
Für uns sind vorallem die Phasen package und clean wichtig.

**Comment by StephanUnfried** [comment]
fertig bei mir

**Comment by StephanUnfried** [comment]
haben alle am projekt beteiligten gemacht
